export const onlineUsers: string='UserOnline'
export const socketId: string='socketId'
export const searchUser: string='searchUser'
export const searchedUser: string='searchedUser'
export const noToken:string='noToken'
export const invalidToken: string='invalidToken'
export const userNotFound: string='userNotFound'
export const emptySearchBar: string='emptySearchBar'